Revert protoc-base bump
Causes compile error, may need to bump proto java version

```
2024-05-10T22:00:28.9028228Z > Task :proto:proto-backplane-grpc:compileJava
2024-05-10T22:00:28.9039719Z /home/runner/work/deephaven-core/deephaven-core/proto/proto-backplane-grpc/build/generated/source/proto/main/java/io/deephaven/proto/backplane/grpc/ConfigurationConstantsResponse.java:38: error: cannot find symbol
2024-05-10T22:00:28.9049578Z   protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
...
```